version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: valeadle
      MYSQL_PASSWORD: honduras760
      MYSQL_ROOT_PASSWORD: contraseña_root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: valeadle
      WORDPRESS_DB_PASSWORD: honduras760
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8080:80"
    volumes:
      - wp_data:/var/www/html
    networks:
      - wp_network

networks:
  wp_network:

volumes:
  db_data:
  wp_data:
